jobs:
- deployment: VMDeploy
  displayName: Web deploy
  environment:
    name: VMenv
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment